In [1]:
import numpy as np

my_list = [20,27,9,12,31,17,4,50,39,35]
arr = np.array(my_list)
print("Multiply by 4:", arr*4)

Multiply by 4: [ 80 108  36  48 124  68  16 200 156 140]


In [2]:
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 24.4
Median: 23.5
Standard Deviation: 13.828955130450023


In [3]:
min_index = np.argmin(arr)
max_index = np.argmax(arr)
print(f"Index of smallest: {min_index}, Index of largest: {max_index}")

Index of smallest: 6, Index of largest: 7


In [4]:
min_val = np.min(arr)
max_val = np.max(arr)
print(f"Smallest value (np.min): {min_val}, Largest value (np.max): {max_val}")

Smallest value (np.min): 4, Largest value (np.max): 50


In [6]:
#Yes they do, at Index 6 the smallest value is there (4), and at Index 7 the largest (50).
more20 = arr[arr > 20]
print(more20)

[27 31 50 39 35]


In [8]:
matrix = np.array([[5,12,17,9],[8,21,14,3],[6,13,19,11]])
print(matrix.shape)

(3, 4)


In [9]:
#3 rows, 4 columns
print(matrix[:, 2])
print(matrix[1, :])
print(matrix*2)

[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [10]:
print(np.mean(matrix, axis=0))
print(np.mean(matrix))
print(np.max(matrix, axis=1))
print(np.min(matrix, axis=0))
flat_mat = matrix.flatten()
print(flat_mat)
print(flat_mat.shape)

[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
(12,)


In [12]:
#A line -- the matrix was flattened into a single array of twelve elements
flat_min_index = np.argmin(matrix)
flat_max_index = np.argmax(matrix)
print(flat_min_index)
print(flat_max_index)
print(np.unravel_index(flat_min_index, matrix.shape))
print(np.unravel_index(flat_max_index, matrix.shape))

7
5
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))


In [13]:
more15 = matrix[matrix > 15]
print(more15)

[17 21 19]


In [14]:
sorted_matrix = np.sort(matrix, axis = 1)
print(sorted_matrix)

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [15]:
arr = np.array([[2,3,5],[14,6,8],[11,13,17],[7,10,13]])
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i ==0:
            return False
    return True

prime_vectors = np.vectorize(is_prime)

def get_prime_rows(arr):
    mask = prime_vectors(arr)
    prime_rows = np.any(mask, axis = 1)
    return arr[prime_rows]

print(get_prime_rows(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [16]:
def checkerboard():
    board = np.zeros((8,8), dtype = int)
    board[0::2, 0::2] = 1
    board[1::2, 1::2] = 1
    return board
print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [17]:
def reverse_checkerboard():
    board = np.zeros((8,8), dtype = int)
    board[0::2, 1::2] = 1
    board[1::2, 0::2] = 1
    return board
print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
def expand(arr, num_spaces):
    spacer = " " * num_spaces
    def expand_word(word):
        return spacer.join(list(word))
    vector_expand = np.vectorize(expand_word)
    return vector_expand(arr)
universe = np.array(['galaxy','clusters'])
expand(universe,1)
expand(universe,2)

array(['g  a  l  a  x  y', 'c  l  u  s  t  e  r  s'], dtype='<U22')

In [21]:
def secondBrightest(star):
    sorted_star = np.sort(star,axis = 1)
    return sorted_star[:, 1]

np.random.seed(123)
star = np.random.randint(500, 2000, (5,5))
print(star)
print(secondBrightest(star))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1622  606  573 1346  951]
